version: '3'

services:
  product-service:
    container_name: 'product-service'
    build: .
    restart: always
    command: ["pm2-runtime", "npm", "--", "run", "start"]
    volumes:
      - .:/app/
      - /app/node_modules
